name: myCardWithFlutter
description: My Business Card With Flutter.


publish_to: 'none'



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

 
  assets:
    - images/

  fonts:
  - family: Raleway
    fonts:
    - asset: fonts/Raleway-VariableFont_wght.ttf

 
  - family: SourceSansPro
    fonts:
    - asset: fonts/SourceSansPro-Black.ttf
  
  - family: SourceSansProBold
    fonts:
    - asset: fonts/SourceSansPro-Bold.ttf
  
  - family: robotoMonoRegular
    fonts:
    - asset: fonts/RobotoMono-Regular.ttf

  - family: pasificoRegular
    fonts:
    - asset: fonts/Pacifico-Regular.ttf
    
  